# hector_mapping_params.yaml
#
# Copyright (C) 2015 Alessandro Francescon
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# The name of the base frame of the robot. This is the frame used for localization and
# for transformation of laser scan data
base_frame: base_link

# The name of the map frame
map_frame: map

# The name of the odom frame
odom_frame: odom

# The map resolution [m]. This is the length of a grid cell edge.
~map_resolution: 0.025

# The size [number of cells per axis] of the map. The map is square and has
# (map_size * map_size) grid cells.
map_size: 1024

# Location of the origin [0.0, 1.0] of the /map frame on the x and y axis relative to the
# grid map. 0.5 is in the middle.
map_start_x: 0.5
map_start_y: 0.5

# Threshold for performing map updates [m]. The platform has to travel this far in meters
# or experience an angular change as described by the map_update_angle_thresh parameter
# since the last update before a map update happens.
map_update_distance_thresh: 0.4
map_update_angle_thresh: 0.9

# The map publish period [s]
map_pub_period: 2.0

# The number of map multi-resolution grid levels
map_multi_res_levels: 3

# The map update modifier for updates of free cells in the range [0.0, 1.0].
# A value of 0.5 means no change.
update_factor_free: 0.4

# The map update modifier for updates of occupied cells in the range [0.0, 1.0].
# A value of 0.5 means no change.
update_factor_occupied: 0.9

# The minimum and maximum distance [m] for laser scan endpoints to be used by the system. 
# Scan endpoints closer than this value are ignored.
laser_min_dist: 0.15
laser_max_dist: 6.0

# The minimum and maximum height [m] relative to the laser scanner frame for laser scan endpoints to
# be used by the system. Scan endpoints lower than this value are ignored.
laser_z_min_value: -1.0
laser_z_max_value: 1.0

# Determine if the map->odom transform should be published by the system
pub_map_odom_transform: true

# Output timing information for processing of every laser scan via ROS_INFO
output_timing: false

# The queue size of the scan subscriber. This should be set to high values (for example 50)
# if logfiles are played back to hector_mapping at faster than realtime speeds.
scan_subscriber_queue_size: 5

# Determines if the scanmatcher to map transform should be published to tf. The frame name
# is determined by the 'tf_map_scanmatch_transform_frame_name' parameter.
pub_map_scanmatch_transform: true
tf_map_scanmatch_transform_frame_name: scanmatcher_frame
