# local_costmap_param.yaml
#
# Copyright (C) 2015 Alessandro Francescon
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

local_costmap:

   # The global frame for the costmap to operate in
  global_frame: odom
  
  # The name of the frame for the base link of the robot
  robot_base_frame: base_link
   
  # The frequency in Hz for the map to be updated
  update_frequency: 5.0
  
  # The frequency in Hz for the map to be publish display information
  publish_frequency: 2.0
  
  # Determines whether or not the costmap should initialize itself based on a map served 
  # by the map_server. If you aren't using an existing map or map server, 
  # set the static_map parameter to false.
  static_map: false
  
  # Whether or not to use a rolling window version of the costmap. 
  # If the static_map parameter is set to true, this parameter must be set to false.
  rolling_window: true
  
  # The width and height in meters and the resolution of the map in meters/cell of the map
  width: 3.0
  height: 3.0
  resolution: 0.05

