# global_costmap_params.yaml
#
# Copyright (C) 2015 Alessandro Francescon
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

global_costmap:

  # The costmap layers dictionary
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # Static layer
  static_layer:
    map_topic: /map
    unknown_cost_value: -1
    lethal_cost_threshold: 100

  # Inflation layer
  inflation_layer:
    inflation_radius: 0.25
    cost_scaling_factor: 50

  # The global frame for the costmap to operate in
  global_frame: map
  
  # The name of the frame for the base link of the robot
  robot_base_frame: base_link
  
  # Whether or not to use a rolling window version of the costmap. 
  # If the static_map parameter is set to true, this parameter must be set to false.
  rolling_window: false
